### ISSUE TITLE
Missing config.yaml

### ISSUE THREAD

**Issue by dmyersturnbull** [MartinThoma/clana#1]
When installing the pip package, I immediately get an error about the `config.yaml` file missing.
Moving [that file](https://raw.githubusercontent.com/MartinThoma/clana/master/clana/config.yaml) to `site-packages/clana` fixed it.

**Comment by chriski777** [comment]
still didn't work. I'm getting this same issue with the latest release of clana

**Comment by MartinThoma** [comment]
@chriski777 Thank you for reporting. I'm not sure why this happens. I hope somebody on StackOverflow knows more about it: https://stackoverflow.com/q/58038169/562769

**Comment by MartinThoma** [comment]
@chriski777 I checked this now more thoroughly. With the `MANIFEST.in` it seems to work. I'm still puzzled why it didn't work before, though.
