### ISSUE TITLE
Links to visualizations are broken

### ISSUE THREAD

**Issue by xssChauhan** [MartinThoma/clana#5]
The following links in README are broken:

1. https://github.com/MartinThoma/clana/blob/master/mnist_confusion_matrix.png
2. https://github.com/MartinThoma/clana/blob/master/mnist_confusion_matrix_labels.png
3. https://github.com/MartinThoma/clana/blob/master/visualizations.md
4. https://github.com/MartinThoma/clana/blob/master/cm-wili-2018.png

**Comment by MartinThoma** [comment]
Thank you for notifying me; I think I fixed it :-)
